[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
backup_core = { path = "../core" }
daemon = { path = "../daemon" }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
dirs = "5"
fs2 = "0.4"
